local ADDON, ns = ...
local PATH = "Interface\\AddOns\\ZenSoundPack\\Sounds\\"
local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("sound", "Zen: Adds", PATH .. "Adds.ogg")
LSM:Register("sound", "Zen: Affix", PATH .. "Affix.ogg")
LSM:Register("sound", "Zen: Avoid", PATH .. "Avoid.ogg")
LSM:Register("sound", "Zen: Avoid Adds", PATH .. "Avoid_Adds.ogg")
LSM:Register("sound", "Zen: Bleed", PATH .. "Bleed.ogg")
LSM:Register("sound", "Zen: Bleed DoT", PATH .. "Bleed_Dot.ogg")
LSM:Register("sound", "Zen: Break Tether", PATH .. "Break_tether.ogg")
LSM:Register("sound", "Zen: Buster", PATH .. "buster.ogg")
LSM:Register("sound", "Zen: CC", PATH .. "CC.ogg")
LSM:Register("sound", "Zen: Cleanse", PATH .. "Cleanse.ogg")
LSM:Register("sound", "Zen: Defensive", PATH .. "defensive.ogg")
LSM:Register("sound", "Zen: Disease", PATH .. "disease.ogg")
LSM:Register("sound", "Zen: Dispel", PATH .. "dispel.ogg")
LSM:Register("sound", "Zen: Dodge", PATH .. "dodge.ogg")
LSM:Register("sound", "Zen: Dodge Swirls", PATH .. "dodge_swirls.ogg")
LSM:Register("sound", "Zen: DoT", PATH .. "dot.ogg")
LSM:Register("sound", "Zen: Everyone Stack", PATH .. "everyone_stack.ogg")
LSM:Register("sound", "Zen: Fly", PATH .. "fly.ogg")
LSM:Register("sound", "Zen: Focus Adds", PATH .. "focus_adds.ogg")
LSM:Register("sound", "Zen: Frontal", PATH .. "frontal.ogg")
LSM:Register("sound", "Zen: Interrupt", PATH .. "interrupt.ogg")
LSM:Register("sound", "Zen: Kick", PATH .. "kick.ogg")
LSM:Register("sound", "Zen: Knock", PATH .. "Knock.ogg")
LSM:Register("sound", "Zen: Magic", PATH .. "magic.ogg")
LSM:Register("sound", "Zen: Magic Buster Inc", PATH .. "magic_buster_inc.ogg")
LSM:Register("sound", "Zen: Magic Damage Inc", PATH .. "magic_damage_inc.ogg")
LSM:Register("sound", "Zen: Magic DoT", PATH .. "magic_dot.ogg")
LSM:Register("sound", "Zen: Magical", PATH .. "magical.ogg")
LSM:Register("sound", "Zen: Mount", PATH .. "mount.ogg")
LSM:Register("sound", "Zen: Move", PATH .. "move.ogg")
LSM:Register("sound", "Zen: Out", PATH .. "out.ogg")
LSM:Register("sound", "Zen: Physical", PATH .. "physical.ogg")
LSM:Register("sound", "Zen: Physical Buster Inc", PATH .. "physical_buster_inc.ogg")
LSM:Register("sound", "Zen: Physical Damage Inc", PATH .. "physical_damage_inc.ogg")
LSM:Register("sound", "Zen: Physical DoT", PATH .. "physical_dot.ogg")
LSM:Register("sound", "Zen: Poison", PATH .. "poison.ogg")
LSM:Register("sound", "Zen: Poison DoT", PATH .. "poison_dot.ogg")
LSM:Register("sound", "Zen: Run", PATH .. "run.ogg")
LSM:Register("sound", "Zen: Run Away", PATH .. "run_away.ogg")
LSM:Register("sound", "Zen: Run Out", PATH .. "run_out.ogg")
LSM:Register("sound", "Zen: Stack", PATH .. "stack.ogg")
LSM:Register("sound", "Zen: Stacking", PATH .. "stacking.ogg")
LSM:Register("sound", "Zen: Stacking Bleed", PATH .. "stacking_bleed.ogg")
LSM:Register("sound", "Zen: Stop", PATH .. "stop.ogg")
LSM:Register("sound", "Zen: Swap", PATH .. "swap.ogg")
LSM:Register("sound", "Zen: Swirls", PATH .. "swirls.ogg")
LSM:Register("sound", "Zen: Tank", PATH .. "tank.ogg")
LSM:Register("sound", "Zen: Tank Buster", PATH .. "tank_buster.ogg")
LSM:Register("sound", "Zen: Taunt", PATH .. "taunt.ogg")
LSM:Register("sound", "Zen: Taunt Now", PATH .. "taunt_now.ogg")
LSM:Register("sound", "Zen: Taunt Soon", PATH .. "taunt_soon.ogg")
LSM:Register("sound", "Zen: Web", PATH .. "web.ogg")
